---
name: nginx

releases:
- name: nginx
  version: latest

stemcells:
# Centos 3421.11 _appears_ not to work under BOSH Lite
- alias: ubuntu
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: nginx
  instances: 1
  azs: [ z1 ]
  vm_type: default
  persistent_disk_type: default
  stemcell: ubuntu
  networks:
  - name: default
    static_ips: [ 10.244.0.34 ]
  jobs:
  - name: nginx
    release: nginx
    properties:
      nginx_conf: |
        user nobody vcap; # group vcap can read most directories
        worker_processes  1;
        error_log /var/vcap/sys/log/nginx/error.log   info;
        events {
          worker_connections  1024;
        }
        http {
          include /var/vcap/packages/nginx/conf/mime.types;
          default_type  application/octet-stream;
          sendfile        on;
          ssi on;
          keepalive_timeout  65;
          server_names_hash_bucket_size 64;
          server {
            server_name _; # invalid value which will never trigger on a real hostname.
            listen *:80;
            # FIXME: replace all occurrences of 'example.com' with your server's FQDN
            access_log /var/vcap/sys/log/nginx/example.com-access.log;
            error_log /var/vcap/sys/log/nginx/example.com-error.log;
            root /var/vcap/data/nginx/document_root;
            index index.shtml;
          }
        }
      pre_start: |
        #!/bin/bash -ex
        NGINX_DIR=/var/vcap/data/nginx/document_root
        if [ ! -d $NGINX_DIR ]; then
          mkdir -p $NGINX_DIR
          cd $NGINX_DIR
          cat > index.shtml <<EOF
            <html><head><title>BOSH on IPv6</title>
            </head><body>
            <h2>Welcome to BOSH's nginx Release</h2>
            <h2>
            My hostname/IP: <b><!--# echo var="HTTP_HOST" --></b><br />
            Your IP: <b><!--# echo var="REMOTE_ADDR" --></b>
            </h2>
            </body></html>
        EOF
        fi
update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
