nginx/headers-more-nginx-module-0.30.tar.gz:
  size: 27793
  object_id: 3eba8c40-b5d6-412d-6726-29129f517b48
  sha: a188a399f3e365a0831585a9d7aa0e6ed1a75f0d
nginx/nginx-1.13.12.tar.gz:
  size: 1016311
  object_id: 3527d5e8-aa5d-4f95-6be8-acc6e7acc019
  sha: ad26921175b28acb8ae6c4eda59050df83279e6e
nginx/nginx-upload-module-2.2.tar.gz:
  size: 28505
  object_id: f5650638-2a55-4602-424d-1b1e6e2d1e8f
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
nginx/pcre-8.40.tar.gz:
  size: 2065161
  object_id: 3c5c62a0-dfdc-46ca-7279-d80161300987
  sha: 10384eb3d411794cc15f55b9d837d3f69e35391e
patches/nginx-upload-module.patch:
  size: 657
  object_id: 27c1b860-1fcf-418a-7342-fca9ac3576c6
  sha: b8733bdb3f0c55a821add0476fb2b477a5a42634
